version: "3.2"
services:
  app:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/srv/app
    stdin_open: true
    tty: true
    ports:
      - 4000:8080
    container_name: math_db_app
    env_file:
      - .env

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
